package com.example.plugin.sdk.model

import com.squareup.moshi.JsonClass

enum class ProviderType {
    TORRENT,
    HTTP,
    EMBED,
    HLS,
    DIRECT_MP4,
    OTHER
}

enum class ProviderHealthStatus {
    READY,
    CONFIGURATION_REQUIRED,
    NETWORK_ERROR,
    API_ERROR,
    NO_RESULTS,
    RATE_LIMITED,
    DISABLED
}

@JsonClass(generateAdapter = true)
data class ProviderConfig(
    val id: String,
    val name: String,
    val enabled: Boolean = true,
    val endpoint: String = "",
    val requiresApiKey: Boolean = false,
    val apiKey: String? = null,
    val supportedMediaTypes: List<String> = listOf("movie", "series", "anime"),
    val supportsDirectStreams: Boolean = true,
    val supportsTorrents: Boolean = false,
    val supportsDebrid: Boolean = false,
    val supportsWebView: Boolean = false,
    val healthStatus: ProviderHealthStatus = ProviderHealthStatus.READY,
    val lastSuccessfulRequest: Long? = null,
    val lastError: String? = null
)

@JsonClass(generateAdapter = true)
data class ProviderResult(
    val providerId: String,
    val status: ProviderHealthStatus,
    val streams: List<PluginVideoStream> = emptyList(),
    val error: String? = null,
    val latencyMs: Long = 0L
)

@JsonClass(generateAdapter = true)
data class StreamSource(
    val providerId: String,
    val name: String,
    val url: String,
    val infoHash: String? = null,
    val magnetUri: String? = null,
    val quality: String? = null,
    val codec: String? = null,
    val size: Long? = null,
    val seeders: Int? = null,
    val sourceType: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val behaviorHints: Map<String, String> = emptyMap()
)

@JsonClass(generateAdapter = true)
data class ProviderCapabilities(
    val supportsSearch: Boolean = true,
    val supportsMovie: Boolean = true,
    val supportsSeries: Boolean = true,
    val supportsAnime: Boolean = false,
    val supportsTorrent: Boolean = false,
    val supportsLive: Boolean = false,
    val supportsSubtitles: Boolean = false,
    val providerType: ProviderType = if (supportsTorrent) ProviderType.TORRENT else ProviderType.OTHER
)

@JsonClass(generateAdapter = true)
data class PluginManifest(
    val id: String,
    val name: String,
    val version: String,
    val author: String,
    val description: String,
    val icon: String? = null,
    val entryFile: String,
    val permissions: List<String> = emptyList(),
    val supportedDomains: List<String> = emptyList(),
    val minimumSDK: Int = 1,
    val signature: String? = null,
    val repository: String? = null
)

@JsonClass(generateAdapter = true)
data class PluginVideoItem(
    val id: String,
    val title: String,
    val uploaderName: String,
    val uploaderUrl: String? = null,
    val uploaderAvatarUrl: String? = null,
    val viewCount: Long = -1,
    val durationSeconds: Long = -1,
    val uploadDate: String? = null,
    val thumbnailUrl: String? = null,
    val providerId: String,
    val description: String? = null
)

@JsonClass(generateAdapter = true)
data class PluginVideoStream(
    val url: String,
    val qualityLabel: String,
    val format: String,
    val width: Int = 0,
    val height: Int = 0,
    val fps: Int = 0,
    val isMuxed: Boolean = false,
    val codec: String? = null,
    val audioUrl: String? = null,
    val headers: Map<String, String> = emptyMap()
)

@JsonClass(generateAdapter = true)
data class PluginAudioStream(
    val url: String,
    val qualityLabel: String,
    val format: String,
    val bitrate: Long = 0,
    val codec: String? = null,
    val language: String? = null,
    val headers: Map<String, String> = emptyMap()
)

@JsonClass(generateAdapter = true)
data class PluginSubtitle(
    val url: String,
    val languageCode: String,
    val languageName: String,
    val format: String,
    val isAutoGenerated: Boolean = false
)

@JsonClass(generateAdapter = true)
data class PluginStreamInfo(
    val id: String,
    val url: String,
    val title: String,
    val channelName: String,
    val channelAvatarUrl: String? = null,
    val viewCount: Long = 0,
    val likeCount: Long = 0,
    val uploadDate: String? = null,
    val description: String? = null,
    val videoStreams: List<PluginVideoStream> = emptyList(),
    val audioStreams: List<PluginAudioStream> = emptyList(),
    val subtitles: List<PluginSubtitle> = emptyList(),
    val hlsUrl: String? = null,
    val httpHeaders: Map<String, String> = emptyMap(),
    val thumbnailUrl: String? = null
)

@JsonClass(generateAdapter = true)
data class PluginComment(
    val id: String,
    val authorName: String,
    val authorAvatarUrl: String? = null,
    val content: String,
    val publishedTime: String? = null,
    val likeCount: Long = 0,
    val replyCount: Long = 0,
    val rating: Float? = null,
    val reviewTitle: String? = null,
    val isSpoiler: Boolean = false,
    val dislikeCount: Long = 0
)

@JsonClass(generateAdapter = true)
data class PluginChannel(
    val id: String,
    val name: String,
    val avatarUrl: String? = null,
    val bannerUrl: String? = null,
    val subscriberCountText: String? = null,
    val description: String? = null,
    val isVerified: Boolean = false
)

@JsonClass(generateAdapter = true)
data class PluginPlaylist(
    val id: String,
    val title: String,
    val uploaderName: String,
    val thumbnailUrl: String? = null,
    val videoCount: Int = 0,
    val videos: List<PluginVideoItem> = emptyList()
)

@JsonClass(generateAdapter = true)
data class PagedResult<T>(
    val items: List<T>,
    val nextPageToken: String? = null,
    val hasMore: Boolean = nextPageToken != null
)
