package com.example.subtitles

import com.example.model.MediaIdentity

/**
 * Metadata search query used to discover subtitles across multiple providers.
 */
data class SubtitleSearchQuery(
    val title: String,
    val year: Int? = null,
    val season: Int? = null,
    val episode: Int? = null,
    val tmdbId: String? = null,
    val imdbId: String? = null,
    val languageCode: String? = null,
    val releaseName: String? = null,
    val mediaIdentity: MediaIdentity? = null
)

enum class SubtitleFormat(val extension: String, val mimeType: String) {
    SRT("srt", "application/x-subrip"),
    VTT("vtt", "text/vtt"),
    ASS("ass", "text/x-ssa"),
    SSA("ssa", "text/x-ssa"),
    JSON("json", "application/json"),
    UNKNOWN("txt", "text/plain")
}

enum class SubtitleSourceType {
    EMBEDDED,
    BILIBILI,
    EXTERNAL_PROVIDER,
    CACHED,
    WHISPER_AI
}

/**
 * Common subtitle item representing a found subtitle track.
 */
data class SubtitleItem(
    val id: String,
    val providerId: String,
    val providerName: String,
    val title: String,
    val languageCode: String,
    val languageName: String,
    val format: SubtitleFormat = SubtitleFormat.SRT,
    val downloadUrl: String,
    val isHearingImpaired: Boolean = false,
    val isAutoGenerated: Boolean = false,
    val matchScore: Int = 100, // 0..100 ranking score
    val sourceType: SubtitleSourceType = SubtitleSourceType.EXTERNAL_PROVIDER,
    val headers: Map<String, String> = emptyMap(),
    val releaseInfo: String? = null
)

/**
 * Common interface for all native Android subtitle providers.
 */
interface SubtitleProvider {
    val id: String
    val name: String
    val isEnabled: Boolean get() = true

    /**
     * Search subtitles for the given video/media query.
     */
    suspend fun search(query: SubtitleSearchQuery): List<SubtitleItem>

    /**
     * Downloads and returns the raw subtitle string content (SRT, VTT, ASS, or JSON).
     */
    suspend fun fetchContent(item: SubtitleItem): String?
}
