package com.example.util

/**
 * Universal UI Strings for English & Hindi UI support.
 * Allows seamless runtime language switching without restarting the app.
 */
object UiStrings {
    // Current active display language code ("en" or "hi")
    var currentLang: String = "en"

    fun get(key: String, lang: String = currentLang): String {
        val map = if (lang == "hi") hindiStrings else englishStrings
        return map[key] ?: englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        "app_name" to "Butterfly",
        "home" to "Home",
        "trending" to "Trending",
        "subscriptions" to "Subscriptions",
        "library" to "Library",
        "settings" to "Settings",
        "search" to "Search",
        "search_hint" to "Search videos, movies, anime, music...",
        "history" to "History",
        "bookmarks" to "Bookmarks",
        "liked_videos" to "Liked Videos",
        "watch_later" to "Watch Later",
        "downloads" to "Downloads",
        "subscribers" to "Subscribers",
        "views" to "views",
        "subscribe" to "Subscribe",
        "subscribed" to "Subscribed",
        "like" to "Like",
        "dislike" to "Dislike",
        "share" to "Share",
        "save" to "Save",
        "download" to "Download",
        "comments" to "Comments",
        "description" to "Description",
        "show_more" to "Show more",
        "show_less" to "Show less",
        "cast_and_crew" to "Cast & Crew",
        "screenshots" to "Screenshots",
        "trailers" to "Trailers & Clips",
        "overview" to "Overview",
        "quality" to "Quality",
        "captions" to "Captions",
        "speed" to "Speed",
        "servers" to "Servers",
        "language_translation" to "Language & Translation",
        "app_language" to "App Display Language",
        "auto_translate_metadata" to "Auto-translate metadata",
        "auto_translate_desc" to "Automatically detect and translate foreign titles and descriptions to English and Hindi",
        "show_original_title" to "Show Original Title",
        "show_translated_title" to "Show Translated Title",
        "original_title" to "Original Title",
        "english_translation" to "English Translation",
        "hindi_translation" to "Hindi Translation",
        "detected_language" to "Detected Language",
        "general" to "General",
        "playback" to "Playback",
        "content_sources" to "Content Sources",
        "cloud_social" to "Cloud & Social",
        "battery_saver" to "Battery Saver",
        "about" to "About",
        "clear_history" to "Clear History",
        "clear_cache" to "Clear Cache",
        "retry" to "Retry",
        "cancel" to "Cancel",
        "confirm" to "Confirm",
        "filter_all" to "All",
        "filter_movies" to "Movies",
        "filter_series" to "Series",
        "filter_anime" to "Anime",
        "filter_music" to "Music",
        "filter_gaming" to "Gaming",
        "filter_news" to "News"
    )

    private val hindiStrings = mapOf(
        "app_name" to "Butterfly",
        "home" to "होम",
        "trending" to "ट्रेंडिंग",
        "subscriptions" to "सदस्यताएँ",
        "library" to "लाइब्रेरी",
        "settings" to "सेटिंग्स",
        "search" to "खोजें",
        "search_hint" to "वीडियो, फिल्में, एनीमे, संगीत खोजें...",
        "history" to "इतिहास",
        "bookmarks" to "बुकमार्क",
        "liked_videos" to "पसंद किए गए वीडियो",
        "watch_later" to "बाद में देखें",
        "downloads" to "डाउनलोड",
        "subscribers" to "सदस्य",
        "views" to "बार देखा गया",
        "subscribe" to "सदस्यता लें",
        "subscribed" to "सदस्यता ली गई",
        "like" to "पसंद करें",
        "dislike" to "नापसंद करें",
        "share" to "शेयर करें",
        "save" to "सहेजें",
        "download" to "डाउनलोड करें",
        "comments" to "टिप्पणियाँ",
        "description" to "विवरण",
        "show_more" to "और दिखाएं",
        "show_less" to "कम दिखाएं",
        "cast_and_crew" to "कलाकार और क्रू",
        "screenshots" to "स्क्रीनशॉट",
        "trailers" to "ट्रेलर और क्लिप",
        "overview" to "अवलोकन",
        "quality" to "गुणवत्ता",
        "captions" to "उपशीर्षक",
        "speed" to "गति",
        "servers" to "सर्वर",
        "language_translation" to "भाषा और अनुवाद",
        "app_language" to "ऐप प्रदर्शन भाषा",
        "auto_translate_metadata" to "मेटाडेटा का स्वतः अनुवाद",
        "auto_translate_desc" to "विदेशी शीर्षकों और विवरणों का स्वचालित रूप से अंग्रेजी और हिंदी में अनुवाद करें",
        "show_original_title" to "मूल शीर्षक दिखाएं",
        "show_translated_title" to "अनुवादित शीर्षक दिखाएं",
        "original_title" to "मूल शीर्षक",
        "english_translation" to "अंग्रेजी अनुवाद",
        "hindi_translation" to "हिंदी अनुवाद",
        "detected_language" to "पहचानी गई भाषा",
        "general" to "सामान्य",
        "playback" to "प्लेबैक",
        "content_sources" to "सामग्री स्रोत",
        "cloud_social" to "क्लाउड और सोशल",
        "battery_saver" to "बैटरी सेवर",
        "about" to "ऐप के बारे में",
        "clear_history" to "इतिहास साफ़ करें",
        "clear_cache" to "कैश साफ़ करें",
        "retry" to "पुनः प्रयास करें",
        "cancel" to "रद्द करें",
        "confirm" to "पुष्टि करें",
        "filter_all" to "सभी",
        "filter_movies" to "फिल्में",
        "filter_series" to "श्रृंखला",
        "filter_anime" to "एनीमे",
        "filter_music" to "संगीत",
        "filter_gaming" to "गेमिंग",
        "filter_news" to "समाचार"
    )
}
